export enum CorruptionType {
    SEVERE,
    VERSATILE,
    EXPEDIENT,
    MASTERFUL,

    SIPHONER,
    AVOIDANT,

    STRIKETHROUGH,
    DEADLY_MOMENTUM,
    HONED_MIND,
    RACING_PULSE,
    SURGING_VITALITY,

    VOID_RITUAL,
    INEFFABLE_TRUTH,
    GLIMPSE_OF_CLARITY,

    INFINITE_STARS,
    ECHOING_VOID,
    TWILIGHT_DEVASTATION,
    TWISTED_APPENDAGE,
    GUSHING_WOUND,


}